[package]
name = "h7dc"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
stm32ral = { version = "0.7", features = ["stm32h747cm7"], default-features = false }
panic-halt = "0.2"
